CREATE USER 'ofbiz'@'%' IDENTIFIED BY "ofbiz#123";

CREATE DATABASE IF NOT EXISTS ofbiz_db DEFAULT CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON ofbiz_db.* TO ofbiz@'%';

CREATE DATABASE IF NOT EXISTS ofbizolap_db DEFAULT CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON ofbizolap_db.* TO ofbiz@'%';

CREATE DATABASE IF NOT EXISTS ofbiztenant_db DEFAULT CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON ofbiztenant_db.* TO ofbiz@'%';

FLUSH PRIVILEGES;
